---

#
# Prepare environment and properties variables
#

- name: Copy environments and properties files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ oracle.user }}"
    group: "{{ oracle.group }}"
  with_items:
    - { src: osb_set_environment_variables.sh.j2 , dest: "{{ osb.scripts_dir }}/osb_set_environment_variables.sh" }
    - { src: osb_environment.properties.j2, dest: "{{ osb.scripts_dir }}/osb_environment.properties" }

#
# Create and configure the OSB cluster
#

- name: Create the OSB cluster
  shell: "{{ osb.scripts_dir }}/osb_create_basic_domain_service.sh > {{ osb.logs_dir }}/create_osb_cluster_$(date +'%F').log 2>&1"

- name: Create AdminServer securtiy directory
  file:
    path: "{{ osb_domain_home }}/servers/AdminServer/security"
    state: directory
    owner: "{{ oracle.user }}"
    group: "{{ oracle.group }}"

- name: Copy AdminServer and Nodemanager properties files
  template:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ oracle.user }}"
    group: "{{ oracle.group }}"
  with_items:
    - { src: boot.properties.j2, dest: "{{ osb_domain_home }}/servers/AdminServer/security/boot.properties" }
    - { src: nodemanager.properties.j2, dest: "{{ osb_nodemanager_home }}/nodemanager.properties" }
    - { src: setUserOverrides.sh.j2, dest: "{{ osb_domain_home }}/bin/setUserOverrides.sh" }
