---

- include: validate.yml
  tags:
    - always

- include: prepare.yml
  become: yes
  become_user: "{{ oracle.user }}"
  when: not osb_already_installed or not osb_already_configured
  tags:
    - always

- include: rcu.yml
  become: yes
  become_user: "{{ oracle.user }}"

- include: install.yml
  become: yes
  become_user: "{{ oracle.user }}"
  when: not osb_already_installed
  tags:
    - osb-plain-install
    - osb-install-and-init

- include: configure.yml
  become: yes
  become_user: "{{ oracle.user }}"
  when: not osb_already_configured
  tags:
    - osb-configure
    - osb-install-and-init

- include: service.yml
  become: yes
  become_user: "{{ oracle.user }}"
  when: not osb_already_configured or osb_init_services
  tags:
    - osb-install-and-init

