---

#
# Manage Nodemanager service
#

- name: Start Nodemanager service
  service:
    name: nodemanager
    state: started
  become: yes
  become_user: root
  tags:
    - osb-start-nodemanager
    - osb-install-and-init

- name: Stop Nodemanager service
  service:
    name: nodemanager
    state: stopped
  become: yes
  become_user: root
  tags:
    - osb-stop-nodemanager

- name: Restart Nodemanager service
  service:
    name: nodemanager
    state: restarted
  become: yes
  become_user: root
  tags:
    - osb-restart-nodemanager

- name: Wait for NodeManager to startup
  wait_for:
    port: "{{ osb_nodemanager_listen_port }}"
    host: "{{ osb_nodemanager_listen_address }}"
    delay: 4
    timeout: 30
  ignore_errors: true
  tags:
    - osb-start-nodemanager
    - osb-restart-nodemanager
    - osb-install-and-init

#
# Manager AdminServer process
#

- name: Start AdminServer
  shell: "{{ osb.scripts_dir }}/osb_control_admin_server.sh start >> {{ osb.logs_dir }}/control_admin_server_$(date +'%F').log 2>&1"
  tags:
    - osb-start-adminserver
    - osb-install-and-init

- name: Stop AdminServer
  shell: "{{ osb.scripts_dir }}/osb_control_admin_server.sh stop >> {{ osb.logs_dir }}/control_admin_server_$(date +'%F').log 2>&1"
  tags:
    - osb-stop-adminserver

- name: Wait for AdminServer to startup
  wait_for:
    port: "{{ osb_admin_server_listen_port }}"
    host: "{{ osb_admin_server_listen_address }}"
    delay: 4
    timeout: 30
  ignore_errors: true
  tags:
    - osb-start-adminserver
    - osb-install-and-init

#
# Manager ManagedServer process
#

- name: Start Managed Server
  shell: "{{ osb.scripts_dir }}/osb_control_managed_servers.sh start >> {{ osb.logs_dir }}/control_managed_servers_$(date +'%F').log 2>&1"
  tags:
    - osb-start-managed-server
    - osb-install-and-init

- name: Stop Managed Server
  shell: "{{ osb.scripts_dir }}/osb_control_managed_servers.sh stop >> {{ osb.logs_dir }}/control_managed_servers_$(date +'%F').log 2>&1"
  tags:
    - osb-stop-managed-server

- name: Wait for Managed Server to startup
  wait_for:
    port: "{{ osb_managed_server_listen_port_start }}"
    host: "{{ osb_managed_server_listen_address }}"
    delay: 4
    timeout: 30
  ignore_errors: true
  tags:
    - osb-start-managed-server
    - osb-install-and-init
